### ISSUE TITLE
check winner function 

### ISSUE THREAD

**Issue by jpotts244** [jpotts244/jpotts244.github.io#2]
Hi Anna, 

Am I on the right track with this part of the function? I am still working on the part that determines if elements from the xarray are in the winners array. Where xarray is the current X's location on the game board.  I cannot get it to return true, I've tried several variations of this, wondering if you would need two arrays going on at the same time? One to iterate through winners array and one going through the xarray at the same time?  Thanks again!!! 

```
var winners = [[0,1,2], [3,4,5], [6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];

var checkWinner = function checkWinner () {
	for (var i = 0; i < winners.length; i++) {
		if (xarray.indexOf(winners[i]) != -1) {
			console.log("true");
			return true;
		} else{
			console.log(false);
			return false;
		}

}
}
```

**Comment by annarankin** [comment]
Hey Jackie! Looks like right now your `xarray.indexOf(winners[i])` condition is checking to see if your `xarray` contains any of the elements in `winners` - which are arrays of numbers, not single numbers. You probably want to change that up so that it checks to see if any of the elements *inside* those elements (ie: `winners[i][0]`) are present in the `xarray` array. Let me know if you want to chat!

**Comment by jpotts244** [comment]
Anna!  I would LOVE to chat, if you don't mind. Let me know and thanks!
